<script setup lang="ts">
import Button from "./components/Button.vue";
const data = {
  label: "Button CTA",
  iconPath:
    "M12.0006 18.26L4.94715 22.2082L6.52248 14.2799L0.587891 8.7918L8.61493 7.84006L12.0006 0.5L15.3862 7.84006L23.4132 8.7918L17.4787 14.2799L19.054 22.2082L12.0006 18.26ZM12.0006 15.968L16.2473 18.3451L15.2988 13.5717L18.8719 10.2674L14.039 9.69434L12.0006 5.27502L9.96214 9.69434L5.12921 10.2674L8.70231 13.5717L7.75383 18.3451L12.0006 15.968Z",
  size: 2,
};
</script>

<template>
  <div class="flex flex-col gap-20">
    <div class="flex flex-row flex-wrap items-center gap-8 font-normal">
      <Button
        :label="data.label"
        :lineHeight="9"
        :font-size="`text-xl`"
        :bg-color="`indigo-700`"
        :color="`white`"
      ></Button>
      <Button
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`left`"
        :font-size="`text-2xl`"
        :lineHeight="1"
        :bg-color="`indigo-700`"
        :color="`white`"
      ></Button>
      <Button
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`right`"
        :font-size="`text-2xl`"
        :lineHeight="9"
        :bg-color="`indigo-700`"
        :color="`white`"
      ></Button>
      <Button
        :label="data.label"
        :font-size="`text-3xl`"
        :lineHeight="15"
        :bg-color="`indigo-700`"
        :color="`white`"
      ></Button>
      <Button
        :icon-path="data.iconPath"
        :size="20"
        :bg-color="`indigo-700`"
        :color="`white`"
      ></Button>
    </div>
    <div class="flex flex-row flex-wrap items-center gap-8 font-medium">
      <Button
        :shadow="`shadow-md`"
        :label="data.label"
        :lineHeight="9"
        :font-size="`text-xl`"
        :bg-color="`white`"
        :color="`stone-700`"
      ></Button>
      <Button
        :shadow="`shadow-md`"
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`left`"
        :font-size="`text-2xl`"
        :lineHeight="1"
        :bg-color="`white`"
        :color="`stone-700`"
      ></Button>
      <Button
        :shadow="`shadow-md`"
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`right`"
        :font-size="`text-2xl`"
        :lineHeight="9"
        :bg-color="`white`"
        :color="`stone-700`"
      ></Button>
      <Button
        :shadow="`shadow-md`"
        :label="data.label"
        :font-size="`text-3xl`"
        :lineHeight="15"
        :bg-color="`white`"
        :color="`stone-700`"
      ></Button>
      <Button
        :shadow="`shadow-md`"
        :icon-path="data.iconPath"
        :size="20"
        :bg-color="`white`"
        :color="`stone-700`"
      ></Button>
    </div>
    <div class="flex flex-row flex-wrap items-center gap-8 font-medium">
      <Button
        :label="data.label"
        :lineHeight="9"
        :font-size="`text-xl`"
        :bg-color="`white`"
        :color="`indigo-700`"
      ></Button>
      <Button
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`left`"
        :font-size="`text-2xl`"
        :lineHeight="1"
        :bg-color="`white`"
        :color="`indigo-700`"
      ></Button>
      <Button
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`right`"
        :font-size="`text-2xl`"
        :lineHeight="9"
        :bg-color="`white`"
        :color="`indigo-700`"
      ></Button>
      <Button
        :label="data.label"
        :font-size="`text-3xl`"
        :lineHeight="15"
        :bg-color="`white`"
        :color="`indigo-700`"
      ></Button>
      <Button
        :icon-path="data.iconPath"
        :size="20"
        :bg-color="`white`"
        :color="`indigo-700`"
      ></Button>
    </div>
    <div class="flex flex-row flex-wrap items-start gap-2 font-medium">
      <Button
        :label="data.label"
        :lineHeight="9"
        :font-size="`text-xl`"
        :bg-color="`white`"
        :color="`indigo-700`"
      ></Button>
      <Button
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`left`"
        :font-size="`text-2xl`"
        :lineHeight="1"
        :bg-color="`white`"
        :color="`indigo-700`"
      ></Button>
      <Button
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`right`"
        :font-size="`text-2xl`"
        :lineHeight="9"
        :bg-color="`white`"
        :color="`indigo-700`"
      ></Button>
      <Button
        :label="data.label"
        :font-size="`text-3xl`"
        :lineHeight="15"
        :bg-color="`white`"
        :color="`indigo-700`"
      ></Button>
      <Button
        :icon-path="data.iconPath"
        :size="20"
        :bg-color="`white`"
        :color="`indigo-700`"
      ></Button>
    </div>
    <div class="flex flex-row flex-wrap items-start gap-2 font-medium">
      <Button
        :label="data.label"
        :lineHeight="9"
        :font-size="`text-xl`"
        :bg-color="`white`"
        :color="`stone-700`"
      ></Button>
      <Button
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`left`"
        :font-size="`text-2xl`"
        :lineHeight="1"
        :bg-color="`white`"
        :color="`stone-700`"
      ></Button>
      <Button
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`right`"
        :font-size="`text-2xl`"
        :lineHeight="9"
        :bg-color="`white`"
        :color="`stone-700`"
      ></Button>
      <Button
        :label="data.label"
        :font-size="`text-3xl`"
        :lineHeight="15"
        :bg-color="`white`"
        :color="`stone-700`"
      ></Button>
      <Button
        :icon-path="data.iconPath"
        :size="20"
        :bg-color="`white`"
        :color="`stone-700`"
      ></Button>
    </div>
    <div class="flex flex-row flex-wrap items-center gap-8 font-normal">
      <Button
        :label="data.label"
        :lineHeight="9"
        :font-size="`text-xl`"
        :bg-color="`red-500`"
        :color="`white`"
      ></Button>
      <Button
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`left`"
        :font-size="`text-2xl`"
        :lineHeight="1"
        :bg-color="`red-500`"
        :color="`white`"
      ></Button>
      <Button
        :label="data.label"
        :icon-path="data.iconPath"
        :icon-position="`right`"
        :font-size="`text-2xl`"
        :lineHeight="9"
        :bg-color="`red-500`"
        :color="`white`"
      ></Button>
      <Button
        :label="data.label"
        :font-size="`text-3xl`"
        :lineHeight="15"
        :bg-color="`red-500`"
        :color="`white`"
      ></Button>
      <Button
        :icon-path="data.iconPath"
        :size="20"
        :bg-color="`red-500`"
        :color="`white`"
      ></Button>
    </div>
  </div>
</template>

<style scoped></style>
